---
  - name: Create backup folder for all related files.
    file: path=/backup/sh state=directory mode=0755

  - name: Copy backup script file to remote server.
    template: src=backupdb.sh.j2 dest=/backup/sh/backupdb.sh owner=root group=root mode=0744

  - name: Set cron job for remote server.
    cron: name="backup db for every site" minute="0" hour="2" cron_file="backup" user="root" job="/backup/sh/backupdb.sh > /dev/null"
