---
# Create a docker container and deploy a site.
- name: Checkout docker-sh repo from github
  git: repo=https://github.com/NETivism/docker-sh.git dest=/etc/ansible/docker-sh accept_hostkey=yes
  tags:
    - start
    - update
  ignore_errors: yes

- name: Update to lastest docker repos
  command: docker pull {{ repos }}
  tags:
    - start
    - update

# update to lastest container
- name: update container
  shell: docker ps -q -f "name={{ domain }}" | xargs --no-run-if-empty -I{} bash -c 'docker exec -i {} bash -c "supervisorctl stop all" && docker stop {} && docker rm {}'
# comment above line, uncomment below line if you meet problem.
#  shell: docker stop {{ domain }} && docker rm {{ domain }}
  tags:
    - update

# normal operation
- name: Deploy a site with mount
  shell: ./docker-start.sh -d {{ domain }} -n {{ site_name }} -l {{ site_mail }} -w {{ port_www }} -m {{ port_db }} -r {{ repos }} -v {{ mount }} -u {{ dbname }} -p {{ passwd }} -s {{ init }} -t {{ size }} chdir=/etc/ansible/docker-sh
  when: mount is defined
  tags:
    - start
    - update

- name: Deploy a site without mount
  shell: ./docker-start.sh -d {{ domain }} -n {{ site_name }} -l {{ site_mail }} -w {{ port_www }} -m {{ port_db }} -r {{ repos }} -u {{ dbname }} -p {{ passwd }} -s {{ init }} -t {{ size }} chdir=/etc/ansible/docker-sh
  when: mount is not defined
  tags:
    - start
    - update

- name: force-reload / restart site
  shell: docker exec -it {{ domain }} bash -c "supervisorctl stop all" && docker restart {{ domain }}
  tags:
    - restart
