---
  - name: Nginx should be started
    service: name=nginx state=started
    tags:
      - start

  - name: Remove default nginx file
    file: path=/etc/nginx/sites-enabled/default state=absent
    tags:
      - start
      - reload

  - name: Copy override config file
    file: path=/etc/nginx/include state=directory mode=0755 owner=answerable
    tags:
      - start
      - reload

# due to bug https://github.com/ansible/ansible-modules-core/issues/1162, change to copy
#  - synchronize: src=/etc/ansible/ansible-docker/playbooks/roles/nginx/files/ dest=/etc/nginx/include archive=no delete=yes recursive=yes
#    tags:
#      - start

  - copy: src={{ item }} dest=/etc/nginx/include/ owner=root mode=644
    with_fileglob:
      - ./*
    tags:
      - start
      - reload 

  - name: Remove default nginx file prevent duplicate
    file: path=/etc/nginx/sites-enabled/0_default state=absent
    tags:
      - start
      - reload 

  - name: Link default file
    file: src=/etc/nginx/include/default_site dest=/etc/nginx/sites-enabled/0_default state=link
    notify:
      - validate nginx
      - reload nginx
    tags:
      - start
      - reload 

  - name: create ssl directory and sync ssl cert
    file: path=/etc/nginx/ssl/neticrm.tw state=directory owner=root mode=0755
    tags:
      - start
      - reload

  - copy: src={{ item }} dest=/etc/nginx/ssl/neticrm.tw/ owner=root mode=400
    with_fileglob:
      - ./ssl/neticrm.tw/*
    tags:
      - start
      - reload
  - name: Check if dhparams exists
    stat: path=/etc/nginx/ssl/dhparams.pem
    register: dhparams
    tags:
      - start
  - name: Generate dhparams when necessery (needs wait awhile)
    shell: openssl dhparam -out /etc/nginx/ssl/dhparams.pem 2048
    when: dhparams.stat.isreg is not defined
    tags:
      - start

  - name: Add Nginx vhost configuration file in sites-available
    # http://docs.ansible.com/template_module.html
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ domain }}
    tags:
      - start

  - name: Link Nginx vhost configuration file in sites-enabled
    action: file src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
    notify:
      - validate nginx
    tags:
      - start

  - name: Generate Nginx redirect configuration file in sites-enabled
    template: src=redirect.conf.j2 dest=/etc/nginx/sites-enabled/0_redirect
    notify:
      - validate nginx
    tags:
      - start
      - reload

  - name: Suspend a website
    template: src=suspend.conf.j2 dest=/etc/nginx/sites-available/{{ domain }}.suspend
    tags:
      - suspend
  - file: path=/etc/nginx/sites-enabled/{{ domain }} state=absent
    tags:
      - suspend
  - action: file src=/etc/nginx/sites-available/{{ domain }}.suspend dest=/etc/nginx/sites-enabled/{{ domain }} state=link
    notify:
      - validate nginx
    tags:
      - suspend

  - name: Remove a site config
    file: path=/etc/nginx/sites-enabled/{{ domain }} state=absent
    tags:
      - remove
  - file: path=/etc/nginx/sites-available/{{ domain }}.suspend state=absent
    notify:
      - validate nginx
    tags:
      - remove
  - file: path=/etc/nginx/sites-available/{{ domain }} state=absent
    notify:
      - validate nginx
    tags:
      - remove

  - name: Reload nginx
    service: name=nginx state=reloaded
    tags:
      - start
      - reload
      - suspend
      - remove
